# coding: utf-8

"""
    Daraa

    This data store is offered by CubeWerx Inc. as a demonstration of its in-progress OGC API implementation.  # noqa: E501

    The version of the OpenAPI document: 9.3.45
    Contact: mgalluch@cubewerx.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CollectionInfoXml(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'title': 'str',
        'description': 'str',
        'links': 'list[LinkXml]',
        'extent_xml': 'LinkXml'
    }

    attribute_map = {
        'name': 'Name',
        'title': 'Title',
        'description': 'Description',
        'links': 'links',
        'extent_xml': 'extent-xml'
    }

    def __init__(self, name=None, title=None, description=None, links=None, extent_xml=None):  # noqa: E501
        """CollectionInfoXml - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._title = None
        self._description = None
        self._links = None
        self._extent_xml = None
        self.discriminator = None

        self.name = name
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        self.links = links
        if extent_xml is not None:
            self.extent_xml = extent_xml

    @property
    def name(self):
        """Gets the name of this CollectionInfoXml.  # noqa: E501


        :return: The name of this CollectionInfoXml.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CollectionInfoXml.


        :param name: The name of this CollectionInfoXml.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def title(self):
        """Gets the title of this CollectionInfoXml.  # noqa: E501


        :return: The title of this CollectionInfoXml.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this CollectionInfoXml.


        :param title: The title of this CollectionInfoXml.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this CollectionInfoXml.  # noqa: E501


        :return: The description of this CollectionInfoXml.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CollectionInfoXml.


        :param description: The description of this CollectionInfoXml.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def links(self):
        """Gets the links of this CollectionInfoXml.  # noqa: E501


        :return: The links of this CollectionInfoXml.  # noqa: E501
        :rtype: list[LinkXml]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this CollectionInfoXml.


        :param links: The links of this CollectionInfoXml.  # noqa: E501
        :type: list[LinkXml]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def extent_xml(self):
        """Gets the extent_xml of this CollectionInfoXml.  # noqa: E501


        :return: The extent_xml of this CollectionInfoXml.  # noqa: E501
        :rtype: LinkXml
        """
        return self._extent_xml

    @extent_xml.setter
    def extent_xml(self, extent_xml):
        """Sets the extent_xml of this CollectionInfoXml.


        :param extent_xml: The extent_xml of this CollectionInfoXml.  # noqa: E501
        :type: LinkXml
        """

        self._extent_xml = extent_xml

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollectionInfoXml):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
