# coding: utf-8

"""
    Daraa

    This data store is offered by CubeWerx Inc. as a demonstration of its in-progress OGC API implementation.  # noqa: E501

    The version of the OpenAPI document: 9.3.45
    Contact: mgalluch@cubewerx.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ConformanceJson(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'conforms_to': 'list[str]'
    }

    attribute_map = {
        'conforms_to': 'conformsTo'
    }

    def __init__(self, conforms_to=None):  # noqa: E501
        """ConformanceJson - a model defined in OpenAPI"""  # noqa: E501

        self._conforms_to = None
        self.discriminator = None

        self.conforms_to = conforms_to

    @property
    def conforms_to(self):
        """Gets the conforms_to of this ConformanceJson.  # noqa: E501

        An array of URLs, where each URL corresponds to a defined OGC Conformance class.  Unrecognized URLs should be ignored.  # noqa: E501

        :return: The conforms_to of this ConformanceJson.  # noqa: E501
        :rtype: list[str]
        """
        return self._conforms_to

    @conforms_to.setter
    def conforms_to(self, conforms_to):
        """Sets the conforms_to of this ConformanceJson.

        An array of URLs, where each URL corresponds to a defined OGC Conformance class.  Unrecognized URLs should be ignored.  # noqa: E501

        :param conforms_to: The conforms_to of this ConformanceJson.  # noqa: E501
        :type: list[str]
        """
        if conforms_to is None:
            raise ValueError("Invalid value for `conforms_to`, must not be `None`")  # noqa: E501

        self._conforms_to = conforms_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConformanceJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
