# coding: utf-8

"""
    Daraa

    This data store is offered by CubeWerx Inc. as a demonstration of its in-progress OGC API implementation.  # noqa: E501

    The version of the OpenAPI document: 9.3.45
    Contact: mgalluch@cubewerx.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class LinkJson(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'href': 'str',
        'rel': 'str',
        'type': 'str',
        'hreflang': 'str',
        'title': 'str'
    }

    attribute_map = {
        'href': 'href',
        'rel': 'rel',
        'type': 'type',
        'hreflang': 'hreflang',
        'title': 'title'
    }

    def __init__(self, href=None, rel=None, type=None, hreflang=None, title=None):  # noqa: E501
        """LinkJson - a model defined in OpenAPI"""  # noqa: E501

        self._href = None
        self._rel = None
        self._type = None
        self._hreflang = None
        self._title = None
        self.discriminator = None

        self.href = href
        if rel is not None:
            self.rel = rel
        if type is not None:
            self.type = type
        if hreflang is not None:
            self.hreflang = hreflang
        if title is not None:
            self.title = title

    @property
    def href(self):
        """Gets the href of this LinkJson.  # noqa: E501


        :return: The href of this LinkJson.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this LinkJson.


        :param href: The href of this LinkJson.  # noqa: E501
        :type: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")  # noqa: E501

        self._href = href

    @property
    def rel(self):
        """Gets the rel of this LinkJson.  # noqa: E501


        :return: The rel of this LinkJson.  # noqa: E501
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """Sets the rel of this LinkJson.


        :param rel: The rel of this LinkJson.  # noqa: E501
        :type: str
        """

        self._rel = rel

    @property
    def type(self):
        """Gets the type of this LinkJson.  # noqa: E501


        :return: The type of this LinkJson.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LinkJson.


        :param type: The type of this LinkJson.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def hreflang(self):
        """Gets the hreflang of this LinkJson.  # noqa: E501


        :return: The hreflang of this LinkJson.  # noqa: E501
        :rtype: str
        """
        return self._hreflang

    @hreflang.setter
    def hreflang(self, hreflang):
        """Sets the hreflang of this LinkJson.


        :param hreflang: The hreflang of this LinkJson.  # noqa: E501
        :type: str
        """

        self._hreflang = hreflang

    @property
    def title(self):
        """Gets the title of this LinkJson.  # noqa: E501


        :return: The title of this LinkJson.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this LinkJson.


        :param title: The title of this LinkJson.  # noqa: E501
        :type: str
        """

        self._title = title

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinkJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
