# coding: utf-8

"""
    Daraa

    This data store is offered by CubeWerx Inc. as a demonstration of its in-progress OGC API implementation.  # noqa: E501

    The version of the OpenAPI document: 9.3.45
    Contact: mgalluch@cubewerx.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ThemesJson(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'links': 'list[LinkJson]',
        'themes': 'list[ThemeJson]',
        'collections': 'list[CollectionInfoJson]'
    }

    attribute_map = {
        'links': 'links',
        'themes': 'themes',
        'collections': 'collections'
    }

    def __init__(self, links=None, themes=None, collections=None):  # noqa: E501
        """ThemesJson - a model defined in OpenAPI"""  # noqa: E501

        self._links = None
        self._themes = None
        self._collections = None
        self.discriminator = None

        self.links = links
        self.themes = themes
        self.collections = collections

    @property
    def links(self):
        """Gets the links of this ThemesJson.  # noqa: E501


        :return: The links of this ThemesJson.  # noqa: E501
        :rtype: list[LinkJson]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ThemesJson.


        :param links: The links of this ThemesJson.  # noqa: E501
        :type: list[LinkJson]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def themes(self):
        """Gets the themes of this ThemesJson.  # noqa: E501


        :return: The themes of this ThemesJson.  # noqa: E501
        :rtype: list[ThemeJson]
        """
        return self._themes

    @themes.setter
    def themes(self, themes):
        """Sets the themes of this ThemesJson.


        :param themes: The themes of this ThemesJson.  # noqa: E501
        :type: list[ThemeJson]
        """
        if themes is None:
            raise ValueError("Invalid value for `themes`, must not be `None`")  # noqa: E501

        self._themes = themes

    @property
    def collections(self):
        """Gets the collections of this ThemesJson.  # noqa: E501


        :return: The collections of this ThemesJson.  # noqa: E501
        :rtype: list[CollectionInfoJson]
        """
        return self._collections

    @collections.setter
    def collections(self, collections):
        """Sets the collections of this ThemesJson.


        :param collections: The collections of this ThemesJson.  # noqa: E501
        :type: list[CollectionInfoJson]
        """
        if collections is None:
            raise ValueError("Invalid value for `collections`, must not be `None`")  # noqa: E501

        self._collections = collections

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ThemesJson):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
