# coding: utf-8

"""
    Daraa

    This data store is offered by CubeWerx Inc. as a demonstration of its in-progress OGC API implementation.  # noqa: E501

    The version of the OpenAPI document: 9.3.45
    Contact: mgalluch@cubewerx.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TilesInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'tile_matrix_set_links': 'list[TilesInfoTileMatrixSetLinks]',
        'links': 'list[LinkJson]'
    }

    attribute_map = {
        'tile_matrix_set_links': 'tileMatrixSetLinks',
        'links': 'links'
    }

    def __init__(self, tile_matrix_set_links=None, links=None):  # noqa: E501
        """TilesInfo - a model defined in OpenAPI"""  # noqa: E501

        self._tile_matrix_set_links = None
        self._links = None
        self.discriminator = None

        self.tile_matrix_set_links = tile_matrix_set_links
        self.links = links

    @property
    def tile_matrix_set_links(self):
        """Gets the tile_matrix_set_links of this TilesInfo.  # noqa: E501


        :return: The tile_matrix_set_links of this TilesInfo.  # noqa: E501
        :rtype: list[TilesInfoTileMatrixSetLinks]
        """
        return self._tile_matrix_set_links

    @tile_matrix_set_links.setter
    def tile_matrix_set_links(self, tile_matrix_set_links):
        """Sets the tile_matrix_set_links of this TilesInfo.


        :param tile_matrix_set_links: The tile_matrix_set_links of this TilesInfo.  # noqa: E501
        :type: list[TilesInfoTileMatrixSetLinks]
        """
        if tile_matrix_set_links is None:
            raise ValueError("Invalid value for `tile_matrix_set_links`, must not be `None`")  # noqa: E501

        self._tile_matrix_set_links = tile_matrix_set_links

    @property
    def links(self):
        """Gets the links of this TilesInfo.  # noqa: E501


        :return: The links of this TilesInfo.  # noqa: E501
        :rtype: list[LinkJson]
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this TilesInfo.


        :param links: The links of this TilesInfo.  # noqa: E501
        :type: list[LinkJson]
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TilesInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
